@startuml
scale 13500 width
scale 2200 height
class 单据 {
}
class 账户 {
    名称
    余额
}
class 收款单 {
    id
    供应商
    操作员
    总额汇总
    单据状态
    创建时间
}
class 收款单转账列表 {
    id
    收款单id
    银行账户
    转账金额备注
}
收款单转账列表 "1...*" --o "1" 收款单
class 付款单 {
    id
    供应商
    操作员
    总额汇总
    单据状态
    创建时间
}
class 付款单转账列表 {
    id
    付款单id
    银行账户
    转账金额备注
}
付款单转账列表 "1...*" --o "1" 付款单
class 工资单 {
    id
    员工姓名
    员工编号
    银行账户
    应发工资
    个人所得税
    失业保险
    住房公积金
    实发金额
    单据状态
    工资单日期
    操作员
    备注
}

class 工资系统 {
    职位
    基本工资
    岗位工资
    薪资计算方式
    发放方式
    失业险比率
    住房公积金比率
}
class 销售明细单 {
    销售操作类型
    id
    商品名
    型号
    数量
    单价
    总额
    创建时间
}
用户 -- 销售明细单: 查看
用户 -- 单据: 查看
经营历程表 "1" o-- "0...*" 单据
class 销售单 {
    id
    客户id
    业务员
    操作员
    备注
    折让前总额
    折让
    使用代金券总额
    折让后总额
    单据状态
    创建时间
}
销售明细单 --|> 销售单
class 销售单商品清单 {
    销售单id
    商品id
    数量
    单价
    总金额
    备注
}
销售单商品清单 "0...*" --o "1" 销售单
class 销售退货单 {
    id
    关联的销售单id
    业务员
    操作员
    备注
    折让前总额
    单据状态
    折让后总额
    折扣
    使用代金券总额
    创建时间
}
class 销售退货单商品清单 {
    销售退货单id
    商品id
    数量
    单价
    总金额
    备注
}
销售退货单商品清单 "0...*" --o "1" 销售退货单
class 进货单 {
    id
    供应商id
    操作员
    备注
    总额合计
    单据状态
    创建时间
}
class 进货单商品清单 {
    进货单id
    商品id
    数量
    单价
    总金额
    备注
}
进货单商品清单 "0...*" --o "1" 进货单
class 进货退货单 {
    id
    关联的进货单id
    操作员
    备注
    退货的总额合计
    单据状态
    创建时间
}
class 进货退货单商品清单 {
    进货退货单id
    商品id
    数量
    单价
    总金额
    备注
}
进货退货单商品清单 "0...*" --o "1" 进货退货单
class 赠送单 {
    id
    销售单id
    商品id
    商品数量
    商品单价
    总价
    状态
}
商品 "1...*" --o "1" 赠送单
赠送单 --|> 单据
class 经营情况表 {
    折让后总收入
    总折让额
    总支出
    总利润
}
class 总支出 {
    销售成本
    商品报损
    商品赠送
    人力成本
    总支出额
}
class 折让后总收入 {
    销售收入
    商品报溢收入
    成本调价收入
    进货退货差价
    代金券与实际收款差额收入
    折让后总收入额
}
总支出 "1" --o "1" 经营情况表
折让后总收入 "1" --o "1" 经营情况表
class 商品 {
    商品id
    商品名
    分类ID
    商品型号
    商品数量
    进价
    零售价
    最近进价
    最近零售价
}
class 员工 {
    员工id
    员工姓名
    性别
    出生日期
    电话号码
    职位
    银行卡号
}
class 打卡 {
    单号
    员工id
    姓名
    打卡日期
}
class 促销策略{}
class 用户级别促销 {
    促销策略id
    用户等级
    折扣
    代金券
    赠品id
    赠品数
    开始时间
    结束时间
}
class 特价包 {
    促销策略id
    商品1的id
    商品1的数量
    商品2的id
    商品2的数量
    降价金额
    开始时间
    结束时间
}
class 总价促销 {
    促销策略id
    满足优惠所需的总价
    代金券
    赠品id
    赠品数
    开始时间
    结束时间
}
用户级别促销 --|> 促销策略
特价包 --|> 促销策略
总价促销 --|> 促销策略
class 年终奖 {
    员工uid
    年份
    前11个月薪资
    年终奖
}
class 用户 {
    用户ID
    用户姓名
    用户密码
    用户身份
}
class 期初建账 {
    商品
    账户
    客户
}
class 客户 {
    id
    分类(供应商\销售商)
    级别
    姓名
    电话号码
    地址
    邮编
    电子邮箱
    应收额度
    应收
    应付
    默认业务员
}
商品 "0...*" --o "1" 期初建账
账户 "0...*" --o "1" 期初建账
客户 "0...*" --o "1" 期初建账
用户 -- 单据: 制定
用户 -- 单据: 审批
用户 -- 年终奖: 制定
用户 -- 促销策略: 制定
用户 -- 工资系统: 制定
用户 -- 工资单: 制定
用户 -- 期初建账: 进行
用户 -- 经营情况表: 查看

收款单 -- 客户: 更新
付款单 -- 客户: 更新

工资单 "1" o-- "1" 工资系统

收款单 --|> 单据
员工 --|> 用户
工资单 "1" --o "1" 员工
年终奖 "1" --o "1" 员工
账户"1" --o "1" 员工

销售单 "1" o-- "0...3" 促销策略

员工 -- 打卡: 进行
工资单 -- 打卡: 根据

付款单 --|> 单据
销售单 --|> 单据
销售退货单 --|> 单据
进货单 --|> 单据
进货退货单 --|> 单据
@enduml