@startuml
skinparam dpi 150
skinparam responseMessageBelowArrow true
actor 总经理
总经理 -> 工资单列表: 审批工资单
alt 通过审批
工资单列表 -> system: 修改工资单状态为审批完成
工资单列表 -> system: 更改员工账户余额
工资单列表 <<-- system: 更新工资单列表
else 未通过审批
工资单列表 -> system: 修改工资单状态为审批失败
工资单列表 <<-- system: 更新工资单列表
end
工资单列表 -->> 总经理: 审批完成
@enduml